#!/bin/bash

#info
version="0.9.27"
dependencies=("make" "texi2html")

#functions
build()
{
	tar xvf tcc-0.9.27.tar.bz2
	cd tcc-0.9.27

	./configure
	make
	make test
}

install()
{
	#preferred privilage escalation utility, sudo, doas, etc.
	root=$1
	
	$root make install
}

uninstall()
{
	#preferred privilage escalation utility, sudo, doas, etc.
	root=$1

	cd tcc-0.9.27
	$root make uninstall
}

#build $1
