#!/bin/bash

#info
version="0.9.27"
dependencies=("make" "texi2html" "wget" "tar" "wget")

#functions
build()
{
	rm -rf tcc
	wget "https://download.savannah.nongnu.org/releases/tinycc/tcc-0.9.27.tar.bz2"
	tar xvf "tcc-$version.tar.bz2"
	cd "tcc-$version"

	./configure
	make
	make test
}

install()
{
	#preferred privilage escalation utility, sudo, doas, etc.
	root=$1
	
	cd "tcc-$version"
	$root make install
}

uninstall()
{
	#preferred privilage escalation utility, sudo, doas, etc.
	root=$1

	cd "tcc-$version"
	$root make uninstall
	cd ..
	rm -rf tcc*
}

#build $1
